language: node_js
node_js:
  - "node"

services:
  - xvfb

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
  - npm install -g @angular/cli

install:
  - npm install

script:
  - ng test --watch=false